# Generated by Django 5.1.3 on 2024-11-21 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Muallif ismini kiriting', max_length=100, verbose_name='Muallif ismi')),
                ('date_of_birth', models.DateField(blank=True, help_text='Tug`ilish sanasini kiriting', null=True, verbose_name='Tug`ilgan sana')),
                ('date_of_death', models.DateField(blank=True, help_text='O`lim sanasini kiriting', null=True, verbose_name='O`lim sanasi')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' Kitob janrini kiriting', max_length=200, verbose_name='Kitob janri')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kitob tilini kiriting', max_length=20, verbose_name='Kitob tili')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kitob nusxasining statusini kiriting', max_length=20, verbose_name='Kitob nusxasi statusi')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kitob nomini kiriting', max_length=200, verbose_name='Kitob nomi')),
                ('summary', models.TextField(help_text='Kitobning qisqacha tavsifini kiriting', max_length=1000, verbose_name='Kitob annotatsiyasi')),
                ('isbn', models.CharField(help_text='13 ta belgidan iborat bo`lishi kerak', max_length=13, verbose_name='kitob ISBNi')),
                ('author', models.ManyToManyField(help_text='Kitob muallifini tanlang', null=True, to='catalog.author', verbose_name='Kitob muallifi')),
                ('genre', models.ForeignKey(help_text='Kitob uchun janrni tanlang', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Kitob janri')),
                ('language', models.ForeignKey(help_text='Kitob uchun tilni tanlang', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Kitob tili')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_nom', models.CharField(help_text='Nusxaning inventar raqamini kiriting', max_length=20, null=True, verbose_name='Inventar raqami')),
                ('imprint', models.CharField(help_text='Nashriyot va nashr yilini kiriting', max_length=200, verbose_name='Nashriyot')),
                ('due_back', models.DateField(blank=True, help_text='Status muddati yakunini kiriting', null=True, verbose_name='Status yakuni sanasi')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text='Nusxa holatini o`zgartirish', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Kitob nusxasi statusi')),
            ],
        ),
    ]
