# Generated by Django 5.1.3 on 2024-11-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Kitob muallifini tanlang', to='catalog.author', verbose_name='Kitob muallifi'),
        ),
    ]
