# Generated by Django 5.1.3 on 2024-11-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='Unknown', help_text='Muallif familiyasini kiriting', max_length=200, verbose_name='Muallif familiyasi'),
        ),
    ]
